title: Robbe Sneyders
description: > # this means to ignore newlines until "baseurl:"
  Robbe Sneyders' personal website. Senior year 
  Masters in Mechanical Engineering, Mechatronics 
  & Robotics. Software developer & Machine learning 
  enthusiast.

google_analytics: UA-92104511-1
